service: hello-world

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  apiName: lambda-go-example
  runtime: go1.x
  stage: production
  region: eu-west-1
  endpointType: REGIONAL
  memorySize: 128
  timeout: 3
  versionFunctions: false

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    name: lambda-go-example-hello
    handler: bin/hello
    events:
      - http:
          path: "/hello"
          method: ANY
          cors: true
